# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Javascript
    steps:
      - name: use Mongo
        uses: supercharge/mongodb-github-action@1.9.0
      - name: Checkout
        uses: actions/checkout@v3
      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: ./Javascript
      - name: run ci
        run: npm ci
        working-directory: ./Javascript
      - name: run coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.2.4
          
