# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Python Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Python
    steps:
      - name: run python
        run: python calculator.py
      - name: run coverage
        run: |
          pip install coverage
          coverage run calculator.py
          coverage report -m
          coverage xml
